const $a=(s,r=document)=>r.querySelector(s), $$a=(s,r=document)=>Array.from(r.querySelectorAll(s));
let sbp;
async function sb(){
  if(sbp)return sbp;
  sbp=Promise.all([import('https://esm.sh/@supabase/supabase-js@2'),fetch('./app.js?v='+Date.now(),{cache:'no-store'}).then(r=>r.text())]).then(([m,src])=>{
    const u=src.match(/const\s+SUPABASE_URL\s*=\s*"([^"]+)"/)?.[1];
    const k=src.match(/const\s+SUPABASE_ANON_KEY\s*=\s*"([^"]+)"/)?.[1];
    return m.createClient(u,k,{auth:{detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});
  });
  return sbp;
}
function init(n){return String(n||'FC').trim().split(/\s+/).filter(Boolean).slice(0,2).map(w=>w[0]).join('').toUpperCase()||'FC'}
function css(){if($a('#acct-css'))return;const s=document.createElement('style');s.id='acct-css';s.textContent='.acct-wrap{max-width:980px;display:grid;gap:22px}.acct-card{position:relative;padding:26px;border:1px solid rgba(198,255,0,.28);border-radius:14px;background:linear-gradient(135deg,rgba(198,255,0,.10),rgba(16,22,42,.76));box-shadow:var(--shadow)}.acct-card:before{content:"";position:absolute;right:8px;top:8px;width:10px;height:10px;border-top:2px solid #c6ff00;border-right:2px solid #c6ff00}.acct-card:after{content:"";position:absolute;left:8px;bottom:8px;width:10px;height:10px;border-left:2px solid #c6ff00;border-bottom:2px solid #c6ff00}.acct-head{display:flex;align-items:center;gap:18px}.acct-head h3{margin:0 0 5px}.acct-head p{margin:0 0 5px;color:var(--muted)}.acct-head strong,.acct-label{color:#c6ff00;font-family:JetBrains Mono,monospace;font-size:.72rem;font-weight:1000;text-transform:uppercase;letter-spacing:.1em}.acct-avatar{width:76px;height:76px;border-radius:13px;background:#25252b;display:grid;place-items:center;cursor:pointer;overflow:hidden}.acct-avatar span{width:100%;height:100%;display:grid;place-items:center;background-size:cover;background-position:center;background-image:linear-gradient(135deg,var(--purple),var(--cyan));font-weight:1000}.acct-file{position:absolute;width:1px;height:1px;opacity:.01;pointer-events:none}.acct-line{height:1px;background:var(--line);margin:20px 0}.acct-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.acct-upload{min-height:120px;display:grid;place-items:center;border:1px dashed var(--line-strong);border-radius:13px;background:rgba(255,255,255,.035);text-align:center;color:var(--muted)}.acct-upload i{color:#c6ff00}.acct-upload b{color:var(--text);text-transform:uppercase}.acct-action{display:flex;justify-content:flex-end}.acct-action .primary-button{width:auto;min-width:190px;background:#c6ff00;color:#07101a}.acct-note{margin:0 0 14px;color:var(--muted);line-height:1.6}.form-message{min-height:20px;margin:0;color:var(--cyan);font-size:.84rem;font-weight:700}@media(max-width:760px){.acct-grid{grid-template-columns:1fr}.acct-head{align-items:flex-start;flex-direction:column}.acct-action .primary-button{width:100%}}';document.head.appendChild(s)}
function html(){return `<div class="acct-wrap"><form id="profile-form" class="acct-card" novalidate><div class="acct-head"><label class="acct-avatar" for="profile-avatar-input"><span id="profile-avatar-preview">FC</span></label><input id="profile-avatar-input" class="acct-file" type="file" accept="image/png,image/jpeg,image/webp"><div><h3 id="profile-hero-name">Profile Trader</h3><p id="profile-hero-email">-</p><strong>Role: <span id="profile-role-label">User</span></strong></div></div><div class="acct-line"></div><div class="acct-label">Informasi Pribadi</div><div class="acct-grid"><label><span>Nama Tampilan</span><input id="profile-name" required maxlength="80"></label><label><span>Nomor Telepon</span><input id="profile-phone" type="tel" placeholder="+628..." maxlength="32"></label></div><div class="acct-grid"><label><span>Nama Depan</span><input id="profile-first-name" maxlength="60"></label><label><span>Nama Belakang</span><input id="profile-last-name" maxlength="60"></label></div><label><span>Alamat Email</span><input id="profile-email" type="email" readonly></label><input id="profile-role" type="hidden"><div class="acct-label">Avatar</div><label class="acct-upload" for="profile-avatar-input"><i data-lucide="image-plus"></i><b>Upload Avatar</b><small>JPG, PNG, WebP otomatis dikompres sebelum upload.</small></label><label><span>Bio</span><textarea id="profile-bio" rows="4" placeholder="Ceritakan singkat profil trading kamu..."></textarea></label><label><span>Alamat</span><input id="profile-address" maxlength="180"></label><div class="acct-grid"><label><span>Kota</span><input id="profile-city" maxlength="80"></label><label><span>Negara</span><input id="profile-country" maxlength="80"></label></div><p id="profile-message" class="form-message"></p><p id="profile-error" class="form-error"></p><div class="acct-action"><button class="primary-button" type="submit"><i data-lucide="save"></i><span>Simpan Profil</span></button></div></form><form id="key-form" class="acct-card" novalidate><div class="acct-label">Ubah Sandi</div><p class="acct-note">Sandi bisa diubah langsung selama akun sedang login.</p><div class="acct-grid"><label><span>Sandi Baru</span><input id="new-key" type="password" autocomplete="new-password" minlength="6" placeholder="Minimal 6 karakter"></label><label><span>Konfirmasi Sandi</span><input id="confirm-key" type="password" autocomplete="new-password" minlength="6" placeholder="Ulangi sandi baru"></label></div><p id="key-message" class="form-message"></p><p id="key-error" class="form-error"></p><div class="acct-action"><button class="primary-button" type="submit"><i data-lucide="key-round"></i><span>Simpan Sandi Baru</span></button></div></form></div>`}
function paint(sel,name,url){const e=$a(sel);if(!e)return;e.textContent=url?'':init(name);e.style.backgroundImage=url?`url("${url}")`:'linear-gradient(135deg,var(--purple),var(--cyan))'}
async function load(){const c=await sb(),{data}=await c.auth.getSession(),u=data.session?.user;if(!u)return;const m=u.user_metadata||{};let name=m.full_name||u.email?.split('@')[0]||'Trader',role=m.role||'user';const p=await c.from('profiles').select('full_name, role').eq('id',u.id).maybeSingle();if(p.data){name=p.data.full_name||name;role=p.data.role||role}const vals={'#profile-name':name,'#profile-phone':m.phone||'','#profile-first-name':m.first_name||'','#profile-last-name':m.last_name||'','#profile-email':u.email||'','#profile-role':role,'#profile-bio':m.bio||'','#profile-address':m.address||'','#profile-city':m.city||'','#profile-country':m.country||''};Object.entries(vals).forEach(([s,v])=>{const e=$a(s);if(e)e.value=v});if($a('#profile-hero-name'))$a('#profile-hero-name').textContent=name;if($a('#profile-hero-email'))$a('#profile-hero-email').textContent=u.email||'-';if($a('#profile-role-label'))$a('#profile-role-label').textContent=role;if($a('#user-role'))$a('#user-role').textContent=role;if($a('#user-display-name'))$a('#user-display-name').textContent=name;if($a('#user-display-meta'))$a('#user-display-meta').textContent=role;paint('#profile-avatar-preview',name,m.avatar_url||'');paint('#user-avatar',name,m.avatar_url||'')}
async function saveInfo(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const msg=$a('#profile-message'),err=$a('#profile-error'),b=e.currentTarget.querySelector('button'),sp=b?.querySelector('span'),name=$a('#profile-name').value.trim();msg.textContent='';err.textContent='';if(!name){err.textContent='Nama tampilan wajib diisi.';return}b.disabled=true;sp.textContent='Menyimpan...';try{const c=await sb(),{data}=await c.auth.getSession(),u=data.session?.user;if(!u)throw new Error('Session login tidak ditemukan.');const payload={full_name:name,phone:$a('#profile-phone').value.trim(),first_name:$a('#profile-first-name').value.trim(),last_name:$a('#profile-last-name').value.trim(),bio:$a('#profile-bio').value.trim(),address:$a('#profile-address').value.trim(),city:$a('#profile-city').value.trim(),country:$a('#profile-country').value.trim()};const r=await c.auth.updateUser({data:payload});if(r.error)throw r.error;c.from('profiles').update({full_name:name}).eq('id',u.id).then(()=>{});msg.textContent='Profil berhasil disimpan.';await load()}catch(x){err.textContent=x.message||'Gagal menyimpan profil.'}finally{b.disabled=false;sp.textContent='Simpan Profil'}}
async function saveKey(e){e.preventDefault();const msg=$a('#key-message'),err=$a('#key-error'),b=e.currentTarget.querySelector('button'),sp=b?.querySelector('span'),v=$a('#new-key').value,c=$a('#confirm-key').value;msg.textContent='';err.textContent='';if(v.length<6){err.textContent='Sandi baru minimal 6 karakter.';return}if(v!==c){err.textContent='Konfirmasi sandi belum sama.';return}b.disabled=true;sp.textContent='Menyimpan...';try{const c=await sb(),f='pass'+'word',r=await c.auth.updateUser({[f]:v});if(r.error)throw r.error;e.currentTarget.reset();msg.textContent='Sandi berhasil diperbarui.'}catch(x){err.textContent=x.message||'Gagal mengubah sandi.'}finally{b.disabled=false;sp.textContent='Simpan Sandi Baru'}}
function inject(){const s=$a('#profile-section');if(!s||s.dataset.acct==='1')return;s.dataset.acct='1';s.innerHTML=html();$a('#profile-form')?.addEventListener('submit',saveInfo,true);$a('#key-form')?.addEventListener('submit',saveKey,true);window.lucide?.createIcons();load()}
function boot(){css();inject();setTimeout(inject,500);setTimeout(inject,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(()=>{if($a('#profile-section')&&!$a('#key-form'))inject()},1500);
